name: Create Droplet on Branch Creation

env:
  DIGITALOCEAN_PROJECT_ID: ${{secrets.DIGITALOCEAN_PROJECT_ID}}

on:
  create:

jobs:
  branch-created:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        # Assuming you want to run a doctl command right after setting it up,
        # you might need to use a `run` step if `args` is not a valid input.
      - name: Create Droplet
        run: |
          DROPLET_ID=$(doctl compute droplet create ${{ github.ref_name }} --size s-1vcpu-1gb --image ubuntu-20-04-x64 --region nyc1 --format ID --no-header --wait)
          echo "DROPLET_ID=$DROPLET_ID" >> $GITHUB_ENV
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Move Droplet to Designated Project
        run: doctl projects resources assign ${{ env.DIGITALOCEAN_PROJECT_ID }} --resource=do:droplet:${{ env.DROPLET_ID }}
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
