name: Destroy Droplet on Branch Deletion

env:
  BRANCH_NAME: ${{ github.event.ref }}

on:
  delete:

jobs:
  destroy-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: "Check if droplet exists"
        run: |
          echo "Checking if droplet exists"
          DROPLET_NAME="${{ env.BRANCH_NAME }}"
          EXISTS=$(doctl compute droplet list --format Name --no-header | grep -w $DROPLET_NAME | wc -l)
          if [ "$EXISTS" -eq 0 ]; then
            echo "DROPLET_EXISTS=false" >> $GITHUB_ENV
          else
            echo "DROPLET_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: Destroy droplet on branch deletion
        if: github.event_name == 'delete' && env.DROPLET_EXISTS == 'true'
        run: |
          echo "Destroying Droplet..."
          DROPLET_ID="${{ env.BRANCH_NAME }}"
          doctl compute droplet delete $DROPLET_ID --force
          echo "${{ env.BRANCH_NAME }} destroyed."

      - name: Delete domain
        if: github.event_name == 'delete' && env.DROPLET_EXISTS == 'true'
        run: doctl compute domain delete pandacalculus.com --force
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Remove SSH key from DigitalOcean
        run: |
          SSH_KEY_ID=$(doctl compute ssh-key list --format ID,Name --no-header | grep "${{ env.BRANCH_NAME }}" | awk '{print $1}')
          if [[ -n "$SSH_KEY_ID" ]]; then
            doctl compute ssh-key delete $SSH_KEY_ID --force
          else
            echo "No SSH key found for deletion."
          fi
