name: Destroy Droplet on Branch Deletion

on:
  delete:

jobs:
  destroy-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Destroy Droplet on Branch Deletion
        if: github.event_name == 'delete'
        run: |
          echo "Destroying Droplet..."
          DROPLET_ID="${{ github.event.ref }}"
          doctl compute droplet delete $DROPLET_ID --force
          echo "${{ github.event.ref }} destroyed."
