name: Destroy Droplet on Branch Deletion

on:
  delete:

jobs:
  destroy-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: "Check if droplet exists"
        run: |
          echo "Checking if droplet exists"
          DROPLET_NAME="${{ github.ref_name }}"
          EXISTS=$(doctl compute droplet list --format Name --no-header | grep -w $DROPLET_NAME | wc -l)
          echo "$DROPLET_NAME"
          if [ "$EXISTS" -eq "0" ]; then
            echo "DROPLET_EXISTS=false" >> $GITHUB_ENV
          else
            echo "DROPLET_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: "Display DROPLIST_EXISTS variable"
        run: |
          echo ${{ env.DROPLIST_EXISTS }}

      - name: Destroy droplet on branch deletion
        if: github.event_name == 'delete' && env.DROPLET_EXISTS == 'true'
        run: |
          echo "Destroying Droplet..."
          DROPLET_ID="${{ github.event.ref_name }}"
          doctl compute droplet delete $DROPLET_ID --force
          echo "${{ github.event.ref_name }} destroyed."
